services:
  postgres_dev:
    container_name: tco-postgres-dev
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Recife
    ports:
      - '5433:5432'
    volumes:
      - tco-postgres-dev:/var/lib/postgresql/data
    networks:
      - tco_dev

volumes:
  tco-postgres-dev:
    external: false

networks:
  tco_dev:
    external: false
