version: "2"
services:
  sentinela-frontend:
    container_name: sentinela-frontend-dev
    command: bash -c "yarn dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
volumes:
  sentinela-frontend-dev:
    external: false
